<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCategorie(){
		// var_dump($this->createQueryBuilder('c'));
		return $this
            ->createQueryBuilder('c')
        ;
	}
}
