<?php

namespace AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll(){
		return $this
            ->createQueryBuilder('t')
            ->getQuery()
        ;	
	}

	public function getTags(){
		return $this
            ->createQueryBuilder('t')
        ;	
	}
}
