# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      app.service_commentaire:
        class: AppBundle\Service\ServiceCommentaire
        arguments: ["@doctrine.orm.entity_manager"]
      app.twig_extension:
        class: AppBundle\Twig\CommentaireExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments: ["@app.service_commentaire"]
